[project]
name = "multisig-wallet"
requirements = []
costs_version = 1

[contracts.multisig]
path = "contracts/multisig.clar"
depends_on = ["traits"]

[contracts.traits]
path = "contracts/traits.clar"
depends_on = []

[contracts.add-owner]
path = "contracts/templates/add-owner.clar"
depends_on = ["multisig"]

[contracts.remove-owner]
path = "contracts/templates/remove-owner.clar"
depends_on = ["multisig"]

[contracts.set-min-confirmation]
path = "contracts/templates/set-min-confirmation.clar"
depends_on = ["multisig"]

[contracts.transfer-stx]
path = "contracts/templates/transfer-stx.clar"
depends_on = ["multisig"]

[contracts.vault]
path = "contracts/helpers/vault.clar"
depends_on = []

[contracts.set-vault-token-per-cycle]
path = "contracts/templates/set-vault-token-per-cycle.clar"
depends_on = ["multisig", "vault"]
