[project]
name = "multisig-wallet"
requirements = []
costs_version = 1

[contracts.wallet]
path = "contracts/wallet.clar"
depends_on = ["traits"]

[contracts.traits]
path = "contracts/traits.clar"
depends_on = []

[contracts.add-owner]
path = "contracts/executors/add-owner.clar"
depends_on = ["wallet"]

[contracts.remove-owner]
path = "contracts/executors/remove-owner.clar"
depends_on = ["wallet"]

[contracts.set-min-confirmation]
path = "contracts/executors/set-min-confirmation.clar"
depends_on = ["wallet"]

[contracts.transfer-stx]
path = "contracts/executors/transfer-stx.clar"
depends_on = ["wallet"]

[contracts.vault]
path = "contracts/helpers/vault.clar"
depends_on = []

[contracts.set-vault-token-per-cycle]
path = "contracts/executors/set-vault-token-per-cycle.clar"
depends_on = ["wallet", "vault"]
