[project]
name = "multisafe"
requirements = []

[repl]
costs_version = 1

[contracts.safe]
path = "contracts/safe.clar"
depends_on = ["traits"]

[contracts.traits]
path = "contracts/traits.clar"
depends_on = []

[contracts.add-owner]
path = "contracts/executors/add-owner.clar"
depends_on = ["safe"]

[contracts.remove-owner]
path = "contracts/executors/remove-owner.clar"
depends_on = ["safe"]

[contracts.set-min-confirmation]
path = "contracts/executors/set-min-confirmation.clar"
depends_on = ["safe"]

[contracts.transfer-stx]
path = "contracts/executors/transfer-stx.clar"
depends_on = ["safe"]

[contracts.vault]
path = "contracts/misc/vault.clar"
depends_on = []

[contracts.set-vault-token-per-cycle]
path = "contracts/executors/set-vault-token-per-cycle.clar"
depends_on = ["safe", "vault"]

